#!/usr/bin/env python

import rospy
from sensor_msgs.msg import Joy
from teaching_interface_ros.msg import TeachingCommand


class Node(object):

    def __init__(self):

        # Variables
        self.grasp_button = False
        self.gripper_grasp = False

        # Parameters
        self.reference = rospy.get_param('~reference', 'base')
        if self.reference not in ['base', 'ee']:
            rospy.logerr("Reference must be 'base' or 'ee'.")
        self.gripper_aperture_limit = rospy.get_param('~gripper_aperture_limit')
        self.gripper_effort_limit = rospy.get_param('~gripper_effort_limit')

        # Initialise publishers
        self.joy_pub = rospy.Subscriber('spacenav/joy', Joy, self.joy_callback, queue_size=1)
        self.tc_pub = rospy.Publisher('~teaching_command', TeachingCommand, queue_size=1)

    def joy_callback(self, msg):
        """
        Callback for the Joy messages received from the 3D mouse.
        Args:
            msg(Joy): Joy message.
        """
        # Construct TeachingCommand message
        tc_msg = TeachingCommand()
        # Reference
        tc_msg.reference = self.reference
        # Twist
        tc_msg.twist.linear.x = msg.axes[0]
        tc_msg.twist.linear.y = msg.axes[1]
        tc_msg.twist.linear.z = msg.axes[2]
        tc_msg.twist.angular.x = msg.axes[3]
        tc_msg.twist.angular.y = msg.axes[4]
        tc_msg.twist.angular.z = msg.axes[5]
        # Gripper command
        if self.grasp_button and not msg.buttons[0]:
            self.gripper_grasp = not self.gripper_grasp
        if self.gripper_grasp:
            tc_msg.gripper_command.position = 0.0
        else:
            tc_msg.gripper_command.position = self.gripper_aperture_limit
        tc_msg.gripper_command.max_effort = self.gripper_effort_limit
        self.grasp_button = msg.buttons[0]
        # Waypoint
        tc_msg.waypoint = msg.buttons[1]
        # Publish message
        self.tc_pub.publish(tc_msg)

    @staticmethod
    def run():
        rospy.spin()


if __name__ == '__main__':
    rospy.init_node('spacenav_joy2tc', anonymous=False)
    n = Node()
    n.run()
